#!/bin/sh
. usr/local/CUT/common.sh
clear
logo

echo "$red DO NOT TOUCH YOUR FLASH CHIP WHILE DOING THIS"
echo "DOING SO HAS A HIGH LIKELYHOOD OF DESTROYING YOUR CHIP, RENDEDRING YOUR SYSTEM UNUSABLE$white"
