name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up dependencies
      run: |
        sudo apt update
        sudo apt install -y wget python3 unzip zip git debootstrap cpio binwalk pcregrep cgpt mkfs.ext4 mkfs.ext2 fdisk depmod findmnt lz4 pv qemu-user-static

    - name: Build Jacuzzi binary
      run: |
        cd scripts
        sudo ./build-complete.sh jacuzzi arch=arm64

    - name: Build Octopus binary
      run: |
        cd scripts
        sudo ./build-complete.sh octopus

    - name: Upload Jacuzzi binary to GitHub Release
      uses: actions/upload-artifact@v3
      with:
        name: CUT-jacuzzi.bin
        path: build/CUT-jacuzzi.bin

    - name: Upload Octopus binary to GitHub Release
      uses: actions/upload-artifact@v3
      with:
        name: CUT-octopus.bin
        path: build/CUT-octopus.bin

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/CUT-jacuzzi.bin
          build/CUT-octopus.bin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
